python3Packages.mlx-{bin,metal}: disable bot updates for Darwin wheels
Fails as follows:
https://nixpkgs-update-logs.nixos.org/python3Packages.mlx-bin/2026-10-06.log

error: mlx-bin: unsupported Python version or system: 3.14-x86_64-linux

Even if we were to fix the update script to work under linux, the bot
won't post an update anyway because it only posts for changes that
produce at least one linux derivation change.